[2025-05-23T18:27:55.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T18:27:55.604+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_pipeline.extract_data scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-05-23T18:27:55.623+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_pipeline.extract_data scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-05-23T18:27:55.624+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-23T18:27:55.659+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data> on 2025-01-22 00:00:00+00:00
[2025-05-23T18:27:55.671+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=217) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-23T18:27:55.673+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-05-23T18:27:55.678+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crypto_etl_pipeline', 'extract_data', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmpuu70ljh6']
[2025-05-23T18:27:55.679+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask extract_data
[2025-05-23T18:27:55.785+0000] {task_command.py:467} INFO - Running <TaskInstance: crypto_etl_pipeline.extract_data scheduled__2025-01-22T00:00:00+00:00 [running]> on host 1b0fd2a9e72d
[2025-05-23T18:27:55.919+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-05-23T18:27:55.924+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-23T18:27:55.925+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-23T18:27:55.926+0000] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2025-05-23 18:27:55.605076+00:00
[2025-05-23T18:27:55.926+0000] {logging_mixin.py:190} INFO - Dag name:crypto_etl_pipeline and current dag run status:running
[2025-05-23T18:27:55.927+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-23T18:27:58.216+0000] {logging_mixin.py:190} INFO -                       datetime crypto currency          price
0   2025-05-23T18:27:55.997453    BTC      USD  109136.795000
1   2025-05-23T18:27:56.070455    BTC      BRL  618205.746766
2   2025-05-23T18:27:56.131410    ETH      USD    2567.650000
3   2025-05-23T18:27:56.212878    ETH      BRL   14552.314584
4   2025-05-23T18:27:56.258208   USDT      USD       1.000235
5   2025-05-23T18:27:56.417356   USDT      BRL       5.664404
6   2025-05-23T18:27:56.591590    BNB      USD     668.607549
7   2025-05-23T18:27:56.748251    BNB      BRL    3786.373579
8   2025-05-23T18:27:56.922548    XRP      USD       2.362600
9   2025-05-23T18:27:57.095047    XRP      BRL      13.379011
10  2025-05-23T18:27:57.262304   DOGE      USD       0.235080
11  2025-05-23T18:27:57.433269   DOGE      BRL       1.331275
12  2025-05-23T18:27:57.598704    SOL      USD     180.235000
13  2025-05-23T18:27:57.988411    SOL      BRL    1020.684021
14  2025-05-23T18:27:58.034320    DOT      USD       4.736000
15  2025-05-23T18:27:58.192728    DOT      BRL      26.820315
[2025-05-23T18:27:58.224+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract.py", line 28, in extract_crypto_data
    df.to_csv('C:/airflow/data/bronze/crypto_prices_raw.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/***/data/bronze'
[2025-05-23T18:27:58.246+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-23T18:27:58.247+0000] {logging_mixin.py:190} INFO - Task start:2025-05-23 18:27:55.605076+00:00 end:2025-05-23 18:27:58.245702+00:00 duration:2.640626
[2025-05-23T18:27:58.263+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: crypto_etl_pipeline> dagrun:<DagRun crypto_etl_pipeline @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-05-23 18:27:48.672481+00:00. externally triggered: False>
[2025-05-23T18:27:58.265+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: 'C:/***/data/bronze'
[2025-05-23T18:27:58.267+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=crypto_etl_pipeline, task_id=extract_data, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250523T182755, end_date=20250523T182758
[2025-05-23T18:27:59.282+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-23T18:27:59.287+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task extract_data (Cannot save file into a non-existent directory: 'C:/***/data/bronze'; 251)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/extract.py", line 28, in extract_crypto_data
    df.to_csv('C:/airflow/data/bronze/crypto_prices_raw.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/***/data/bronze'
[2025-05-23T18:27:59.394+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-23T18:27:59.440+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T18:27:59.454+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
